# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  IMAGE_PLATFORMS: linux/amd64,linux/arm64
  IMAGE_TAG: dev

tasks:
  build:
    internal: true
    desc: Build the Docker image for the local platform and load it into Docker
    requires:
      vars: [IMAGE_NAME, IMAGE_TAG]
    cmd: |
      docker buildx build \
        --tag="{{.IMAGE_NAME}}:{{.IMAGE_TAG}}" \
        --pull \
        --load \
        .

  push:
    desc: Build the Docker image for multiple platforms and push it to the registry
    requires:
      vars: [IMAGE_PLATFORMS, IMAGE_NAME, IMAGE_TAG]
    cmd: |
      docker buildx build \
        --platform="{{.IMAGE_PLATFORMS}}" \
        --tag="{{.IMAGE_NAME}}:{{.IMAGE_TAG}}" \
        --pull \
        --push \
        .
