# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  IMAGE_TAG: dev
  IMAGE_PLATFORMS: linux/amd64,linux/arm64

tasks:
  build:
    internal: true
    desc: Build the Docker image and load it into Docker
    requires:
      vars: [IMAGE_PLATFORMS, IMAGE_NAME, IMAGE_TAG]
    cmd: |
      docker buildx build \
        --platform {{.IMAGE_PLATFORMS}} \
        --tag "{{.IMAGE_NAME}}:{{.IMAGE_TAG}}" \
        --pull \
        --load \
        .
