# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  IMAGE_TAG: dev

tasks:
  build:
    internal: true
    desc: Build the Docker image for the local platform and load it into Docker
    requires:
      vars: [IMAGE_NAME, IMAGE_TAG]
    cmd: >-
      docker buildx build --pull --load
      --tag="{{.IMAGE_NAME}}:{{.IMAGE_TAG}}"
      .
