nodeLinker: hoisted
packageManagerStrictVersion: true

allowedDeprecatedVersions:
  # Transient dependencies via grpc-tools -> @mapbox/node-pre-gyp
  # See https://github.com/grpc/grpc-node/issues/2968
  are-we-there-yet: "2"
  gauge: "3"
  glob: "7"
  inflight: "1"
  npmlog: "5"
  rimraf: "3"

onlyBuiltDependencies:
  - cpu-features
  - esbuild
  - grpc-tools
  - protobufjs
  - sharp
  - ssh2
  - unrs-resolver
