minimumReleaseAge: 4320 # 3 days in minutes
nodeLinker: hoisted
packageManagerStrictVersion: true

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - cpu-features
  - esbuild
  - protobufjs
  - sharp
  - ssh2
  - unrs-resolver

minimumReleaseAgeExclude:
  - "*vitest*"
  - "*storybook*"
