minimumReleaseAge: 4320 # 3 days in minutes
nodeLinker: hoisted
packageManagerStrictVersion: true
useNodeVersion: 24.10.0

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - sharp
  - unrs-resolver
