# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  APP_NAME: nextjs-starter
  GENERATED_FILES: ENVIRONMENT.md
  IMAGE_NAME: ghcr.io/ezzatron/nextjs-starter

includes:
  docker: ./taskfiles/docker
  eslint: ./taskfiles/js/eslint.Taskfile.yml
  js: ./taskfiles/js
  next: ./taskfiles/js/next.Taskfile.yml
  prettier: ./taskfiles/js/prettier.Taskfile.yml
  tsc: ./taskfiles/js/tsc.Taskfile.yml

tasks:
  install-deps:
    desc: Install dependencies
    aliases: [install, i, deps]
    cmds:
      - task: js:install-deps

  run:dev:
    desc: Run the app in development mode
    aliases: [run, dev]
    cmds:
      - task: next:run

  run:prod:
    desc: Run the app in production mode
    aliases: [start, prod]
    deps: [build]
    cmd: node out/dist/run.mjs

  run:container:
    desc: Run the app in a container
    deps: [image]
    cmds:
      - "docker run --rm -it -p 8000:8000 {{.IMAGE_NAME}}:{{.IMAGE_TAG}}"

  lint:
    desc: Run formatting, linting, and type checking
    cmds:
      - task: prettier:write
      - task: eslint:check
      - task: tsc:typecheck

  docs:environment:
    desc: Generate environment variable usage documentation
    deps: [js:install-deps]
    sources:
      - src/env.ts
      - src/run.ts
      - package.json
    generates:
      - ENVIRONMENT.md
    env:
      AUSTENITE_MODE: usage/markdown
      AUSTENITE_APP: "{{.APP_NAME}}"
    cmd: node --experimental-strip-types src/run.ts > ENVIRONMENT.md

  regenerate:
    desc: Regenerate all generated files
    cmds:
      - rm -rf {{.GENERATED_FILES}}
      - task: docs:environment

  regenerate:check:
    internal: true
    desc: Check if all generated files are up to date
    deps: [regenerate]
    preconditions:
      - sh: git diff --exit-code -- {{.GENERATED_FILES}}
        msg: Generated files are out of date
    cmd: echo All generated files are up to date

  build:
    desc: Build the app for production
    deps: [next:build:standalone]
    sources:
      - out/next/standalone/**
    generates:
      - out/dist/**
    cmds:
      - rm -rf out/dist
      - cp -a out/next/standalone out/dist
      - node --experimental-strip-types src/build-run.ts out/dist/run.mjs

  image:
    desc: Build the container image
    aliases: [docker]
    deps: [build]
    cmds:
      - task: docker:build

  precommit:
    desc: Run all pre-commit checks
    aliases: [pc]
    cmds:
      - task: regenerate:check
      - task: prettier:write
      - task: eslint:no-warnings
      - task: tsc:typecheck
      - task: build
      - task: docker:build

  ci:
    desc: Run all continuous integration checks
    cmds:
      - task: regenerate:check
      - task: build
      - task: docker:build
      - task: prettier:check
      - task: eslint:no-warnings
      - task: tsc:typecheck
