# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  IMAGE_NAME: fixme

includes:
  docker: ./taskfiles/docker
  eslint: ./taskfiles/js/eslint.Taskfile.yml
  js: ./taskfiles/js
  next: ./taskfiles/js/next.Taskfile.yml
  prettier: ./taskfiles/js/prettier.Taskfile.yml
  tsc: ./taskfiles/js/tsc.Taskfile.yml

tasks:
  install-deps:
    desc: Install dependencies
    aliases: [install, i]
    cmds:
      - task: js:install-deps

  run-dev:
    desc: Run the app in development mode
    aliases: [run, dev]
    cmds:
      - task: next:run

  run-prod:
    desc: Run the app in production mode
    aliases: [start, prod]
    cmds:
      - task: next:start:standalone

  lint:
    desc: Run formatting, linting, and type checking
    cmds:
      - task: prettier:write
      - task: eslint:check
      - task: tsc:typecheck

  build:
    desc: Build the app for production
    cmds:
      - task: next:build:standalone

  image:
    desc: Build the container image
    aliases: [docker]
    deps: [build]
    cmds:
      - task: docker:build

  precommit:
    desc: Run all pre-commit checks
    aliases: [pc]
    cmds:
      - task: prettier:write
      - task: eslint:no-warnings
      - task: tsc:typecheck
      - task: build
      - task: docker:build

  ci:
    desc: Run all continuous integration checks
    cmds:
      - task: build
      - task: docker:build
      - task: prettier:check
      - task: eslint:no-warnings
      - task: tsc:typecheck
