# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

run: when_changed

vars:
  APP_NAME: nextjs-starter
  IMAGE_NAME: ghcr.io/ezzatron/nextjs-starter
  IMAGE_TAG: dev
  JS_EXEC: pnpm exec --
  PW_TEST_CONNECT_EXPOSE_NETWORK: <loopback>
  PW_TEST_CONNECT_WS_ENDPOINT: ws://localhost:7357
  PW_TEST_PROJECTS: []
  VITEST_PROJECTS: []

env:
  IMAGE_REFERENCE: "{{.IMAGE_NAME}}:{{.IMAGE_TAG}}"
  NEXT_TELEMETRY_DISABLED: "1"

tasks:
  install-deps:
    desc: Install dependencies
    aliases: [install, i, deps]
    sources:
      - pnpm-lock.yaml
    generates:
      - node_modules/**
    cmd: pnpm install --frozen-lockfile

  run:dev:
    desc: Run the app in development mode
    aliases: [run, dev]
    deps: [install-deps]
    dotenv: [env/run.local.env, env/run.env]
    cmd: "{{.JS_EXEC}} next dev --turbopack"

  run:prod:
    desc: Run the app in production mode
    aliases: [start, prod]
    deps: [build:next]
    dotenv: [env/run.local.env, env/run.env]
    cmd: node out/next/standalone/server.js

  run:container:
    desc: Run the app in a container
    deps: [build:image]
    vars:
      HAS_LOCAL_ENV:
        sh: test -f env/run.container.local.env && echo "true" || echo ""
    cmd: >-
      docker run
      --add-host=host.docker.internal:host-gateway
      --rm
      --interactive
      --tty
      --publish=3000:3000
      --env-file=env/run.container.env
      {{if .HAS_LOCAL_ENV}}--env-file=env/run.container.local.env{{end}}
      {{.IMAGE_NAME}}:{{.IMAGE_TAG}}

  open:
    desc: Open the app in development mode in the default browser
    aliases: [browse]
    cmd:
      task: util:open
      vars:
        TARGET: http://localhost:3000

  storybook:dev:
    desc: Run Storybook in development mode
    aliases: [storybook]
    deps: [install-deps]
    cmd: "{{.JS_EXEC}} storybook dev --port=6006"

  storybook:build:
    desc: Build Storybook
    deps: [install-deps]
    cmd: "{{.JS_EXEC}} storybook build --output-dir=out/storybook"

  test:
    desc: Run all test suites
    aliases: [t, default]
    cmds:
      - task: test:vitest
      - task: test:playwright

  test:playwright:
    desc: Run Playwright tests
    aliases: [playwright]
    deps: [install-deps, build:image]
    env:
      PW_TEST_CONNECT_WS_ENDPOINT: "{{.PW_TEST_CONNECT_WS_ENDPOINT}}"
      PW_TEST_CONNECT_EXPOSE_NETWORK: "{{.PW_TEST_CONNECT_EXPOSE_NETWORK}}"
    cmd: >-
      {{.JS_EXEC}} playwright test
      {{if .PW_TEST_HEADED}}--headed{{end}}
      {{if .PW_TEST_IGNORE_SNAPSHOTS}}--ignore-snapshots{{end}}
      {{if .PW_TEST_UI}}--ui{{end}}
      {{if .PW_TEST_FORBID_ONLY}}--forbid-only{{end}}
      {{range .PW_TEST_PROJECTS}} --project="{{.}}"{{end}}

  test:playwright:all:
    desc: Run Playwright tests for all projects
    aliases: [playwright:all]
    cmds:
      - task: test:playwright
        vars:
          PW_TEST_PROJECTS:
            - chromium
            - firefox
            - webkit

  test:playwright:headed:
    desc: Run Playwright tests in headed mode
    aliases: [playwright:headed]
    cmds:
      - task: test:playwright
        vars:
          PW_TEST_CONNECT_EXPOSE_NETWORK: ""
          PW_TEST_CONNECT_WS_ENDPOINT: ""
          PW_TEST_HEADED: true
          PW_TEST_IGNORE_SNAPSHOTS: true

  test:playwright:ui:
    desc: Run Playwright tests in UI mode
    aliases: [playwright:ui]
    cmds:
      - task: test:playwright
        vars:
          PW_TEST_UI: true

  test:playwright:report:
    desc: Show the HTML report from the last test run
    aliases: [playwright:report]
    deps: [install-deps]
    cmd: "{{.JS_EXEC}} playwright show-report out/playwright/report/html"

  test:playwright:ci:
    desc: Run Playwright tests for continuous integration
    deps: [install-deps] # Image is expected to be pre-built under CI
    env:
      PW_TEST_CONNECT_WS_ENDPOINT: "{{.PW_TEST_CONNECT_WS_ENDPOINT}}"
      PW_TEST_CONNECT_EXPOSE_NETWORK: "{{.PW_TEST_CONNECT_EXPOSE_NETWORK}}"
    cmd: >-
      {{.JS_EXEC}} playwright test
      --forbid-only
      --project=chromium
      --project=firefox
      --project=webkit

  test:vitest:
    desc: Run Vitest tests
    aliases: [vitest]
    deps: [install-deps]
    cmd: >-
      {{.JS_EXEC}} vitest
      {{if .VITEST_UI}}--ui{{end}}
      {{if .VITEST_WATCH}}--watch{{end}}
      {{if .VITEST_COVERAGE}}--coverage.enabled --coverage.reportsDirectory=out/vitest/coverage{{end}}
      {{if .VITEST_COVERAGE}}--coverage.reporter=lcov --coverage.reporter=text{{end}}
      {{if .VITEST_FORBID_ONLY}}--allowOnly=false{{end}}
      {{range .VITEST_PROJECTS}} --project="{{.}}"{{end}}

  test:vitest:watch:
    desc: Run Vitest tests in watch mode
    aliases: [vitest:watch]
    cmds:
      - task: test:vitest
        vars:
          VITEST_WATCH: true

  test:vitest:ui:
    desc: Run Vitest tests in UI mode
    aliases: [vitest:ui]
    cmds:
      - task: test:vitest
        vars:
          VITEST_UI: true
          VITEST_WATCH: true

  test:vitest:coverage:
    desc: Run Vitest tests with coverage
    aliases: [test:coverage, vitest:coverage, coverage]
    cmds:
      - task: test:vitest
        vars:
          VITEST_COVERAGE: true

  test:vitest:coverage:open:
    desc: Open the Vitest coverage report
    aliases: [test:coverage:open, vitest:coverage:open, coverage:open]
    cmds:
      - task: util:open
        vars:
          TARGET: out/vitest/coverage/lcov-report/index.html

  test:vitest:ci:
    desc: Run Vitest tests for continuous integration
    cmds:
      - task: test:vitest
        vars:
          VITEST_COVERAGE: true
          VITEST_FORBID_ONLY: true
          VITEST_PROJECTS:
            - chromium
            - firefox
            - server
            - storybook
            - webkit

  test:services:up:
    desc: Start the test services
    aliases: [test:services]
    cmds:
      - docker compose --file=test/api/docker-compose.yml up --wait
      - docker compose --file=test/playwright/server/docker-compose.yml up --wait

  test:services:down:
    desc: Stop the test services
    cmds:
      - docker compose --file=test/api/docker-compose.yml down
      - docker compose --file=test/playwright/server/docker-compose.yml down

  test:services:build:
    desc: Build the test services
    cmds:
      - docker compose --file=test/api/docker-compose.yml build
      - docker compose --file=test/playwright/server/docker-compose.yml build

  lint:
    desc: Run formatting, linting, and type checking
    aliases: [l]
    cmds:
      - task: lint:prettier:write
      - task: lint:eslint:check
      - task: lint:typecheck

  lint:eslint:check:
    desc: Check linting with ESLint, allowing warnings
    aliases: [eslint:check, eslint]
    deps: [install-deps]
    cmd: "{{.JS_EXEC}} eslint"

  lint:eslint:strict:
    desc: Check linting with ESLint, failing on warnings
    aliases: [eslint:strict]
    deps: [install-deps]
    cmd: "{{.JS_EXEC}} eslint --max-warnings=0"

  lint:prettier:check:
    desc: Check formatting with Prettier
    aliases: [prettier:check]
    deps: [install-deps]
    cmd: "{{.JS_EXEC}} prettier --check ."

  lint:prettier:write:
    desc: Automatically fix formatting with Prettier
    aliases: [prettier:write]
    deps: [install-deps]
    cmd: "{{.JS_EXEC}} prettier --write ."

  lint:generated:
    desc: Check if all generated files are up to date
    deps: [regenerate]
    preconditions:
      - sh: git diff --exit-code -- ENVIRONMENT.md src/api/gen
        msg: Generated files are out of date
    cmd: echo All generated files are up to date

  lint:typecheck:
    desc: Check types with TypeScript
    aliases: [typecheck]
    deps: [install-deps]
    cmd: "{{.JS_EXEC}} tsc --noEmit"

  regenerate:
    desc: Regenerate all generated files
    aliases: [regen]
    cmds:
      - task: clean:generated
      - task: build:proto
      - task: build:environment

  build:next:
    desc: Build the app for production
    aliases: [build]
    deps: [build:proto]
    sources:
      - public/**
      - src/**
      - next.config.ts
      - pnpm-lock.yaml
      - postcss.config.js
      - tsconfig.json
      - exclude: src/**/*.{stories,test}.*
    generates:
      - .next/**
      - out/next/standalone/**
    cmds:
      - "{{.JS_EXEC}} next build --turbopack"
      - rm -rf out/next/standalone
      - mkdir -p out/next
      - cp -r .next/standalone out/next/standalone
      - mkdir -p out/next/standalone/.next
      - cp -r .next/cache out/next/standalone/.next/cache
      - cp -r .next/static out/next/standalone/.next/static
      - cp -r public out/next/standalone/

  build:analyze:
    desc: Analyze the production app bundles
    aliases: [analyze]
    deps: [install-deps]
    env:
      ANALYZE: "true"
    cmds:
      - "{{.JS_EXEC}} next build --webpack"
      - cp -r .next/analyze out/next/analyze
      - rm -rf .next

  build:analyze:open:
    desc: Analyze the production app bundles
    aliases: [analyze:open]
    cmds:
      - task: util:open
        vars:
          TARGET: out/next/analyze/client.html

  build:image:
    desc: Build the container image
    aliases: [image, docker]
    deps: [build:next]
    method: timestamp
    sources:
      - .dockerfile
      - Dockerfile
      - out/next/standalone/**
    generates:
      - out/image.touch
    cmds:
      - >-
        docker buildx build --pull --load
        --tag="{{.IMAGE_NAME}}:{{.IMAGE_TAG}}"
        .
      - mkdir -p out
      - touch out/image.touch

  build:proto:
    desc: Compile .proto files
    aliases: [proto]
    deps: [install-deps]
    sources:
      - src/api/**/*.proto
    generates:
      - src/api/gen/**
    cmds:
      - mkdir -p src/api/gen/pet-store
      - >-
        {{.JS_EXEC}} grpc_tools_node_protoc
        --plugin=protoc-gen-ts_proto=./node_modules/.bin/protoc-gen-ts_proto
        --proto_path=src/api
        --descriptor_set_out=src/api/gen/pet-store/v1.pb
        --ts_proto_out=src/api/gen
        --ts_proto_opt="outputServices=nice-grpc,outputServices=generic-definitions,useExactTypes=false"
        src/api/pet-store/v1.proto
      - node src/api/strip-protoc-versions.ts

  build:environment:
    desc: Generate environment variable usage documentation
    deps: [install-deps]
    sources:
      - src/env.ts
    generates:
      - ENVIRONMENT.md
    env:
      AUSTENITE_MODE: usage/markdown
      AUSTENITE_APP: "{{.APP_NAME}}"
    cmd: node src/env.ts > ENVIRONMENT.md

  pre-commit:
    desc: Run all pre-commit checks
    aliases: [pc]
    cmds:
      - task: lint:generated
      - task: lint:prettier:write
      - task: lint:eslint:strict
      - task: lint:typecheck
      - task: test:vitest
        vars:
          VITEST_FORBID_ONLY: true
          VITEST_PROJECTS:
            - chromium
            - firefox
            - server
            - storybook
            - webkit
      - task: build:image
      - task: test:playwright
        vars:
          PW_TEST_FORBID_ONLY: true
          PW_TEST_PROJECTS:
            - chromium
            - firefox
            - webkit

  clean:ignored:
    desc: Clean all ignored files
    aliases: [clean]
    cmds:
      - rm -rf node_modules # Git has trouble with this for some reason
      - git clean -fdx

  clean:generated:
    desc: Clean all generated files
    cmd: rm -rf ENVIRONMENT.md src/api/gen

  clean:all:
    desc: Clean all generated and ignored files
    cmds:
      - task: clean:ignored
      - task: clean:generated

  util:open:
    desc: Open the supplied file or URL with the default application
    requires:
      vars: [TARGET]
    cmds:
      - platforms: [darwin]
        cmd: open "{{.TARGET}}"
      - platforms: [linux]
        cmd: xdg-open "{{.TARGET}}"
      - platforms: [windows]
        cmd: cmd /c start "{{.TARGET}}"
