# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  pnpm: ./pnpm.Taskfile.yml

tasks:
  install-deps:
    internal: true
    desc: Install JavaScript dependencies
    deps: [pnpm:install]
