# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

env:
  JS_EXEC: npm exec --

includes:
  npm: ./npm.Taskfile.yml

tasks:
  install-deps:
    desc: Install JavaScript dependencies
    deps: [npm:install]
